version: '3.8'

services:
  postgres:
    image: postgres:16  # Versión estable más reciente
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P3_!T9ZT6beV-xU
      POSTGRES_DB: Db_LegalisFlow
    ports:
      - "5432:5432"  # Mapea el puerto de PostgreSQL
    volumes:
      - pg_data:/var/lib/postgresql/data  # Persistencia de datos
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_data:  # Volumen para guardar datos de PostgreSQL